### PR TITLE
global: redis host command line argument

### PR DESCRIPTION
**Pull request by ddaze**
Signed-off-by: David Zerulla <ddaze@outlook.de>

### CODE REVIEW

**Comment by frecar** [comment]
Looking good! :) But should we also be able to provide redis password?

**Comment by ddaze** [comment]
I don’t think so, the redis host is only accessible by the worker nodes.

**Comment by frecar** [comment]
But it might be different on different installations of Invenio :)

**Comment by egabancho** [comment]
I think no matter how your installation (server architecture) is you should be able to use iptables to allow/deny access to the redis server depending on the origin of the request. 

Inside Invenio we don't use password either :wink:

**Comment by frecar** [comment]
Sure, okey! Let's merge then :hammer:

**Pull request merged**
