### PR TITLE
global: Travis configuration

### PR DESCRIPTION
**Pull request by ddaze**

### CODE REVIEW

**Comment by frecar** [comment]
Why would we need Travis? :) Frigg is testing it already

**Comment by ddaze** [comment]
Frigg is not loading (maybe because of the slow wlan) so I added Travis for the tests.
Can I also add Frigg for my repositories?

**Comment by frecar** [comment]
Yes, just add https://ci.frigg.io/webhooks/github/ as a webhook :)

**Comment by crepererum** [comment]
Frigg webinterface is broken, at least on Firefox (39.0). Go to `https://ci.frigg.io/` and get the following JS error 3 times: `TypeError: Not enough arguments to EventTarget.addEventListener.`. The interface only shows the "loading"-spinner.

**Comment by frecar** [comment]
@crepererum I will look into it. Unfortunately, Firefox has not been tested properly!  I will come back to you soon (today).

**Comment by frecar** [comment]
@crepererum @ddaze please try with Firefox now! :)

**Comment by crepererum** [comment]
Works now (if you consider the `prototype`, `map` and `sha1 security` warning as not important).

**Comment by frecar** [comment]
Great, no they are not that important for the time being! :)

**Comment by egabancho** [comment]
I think we should reopen this PR (and maybe add more things to it, i.e. built the documentation)

I know that you are using  Frigg for your (Tind) projects but if you look around inside Inveniosoftware you'll see that Travis is used everywhere (I love consistency)

**Comment by frecar** [comment]
I will make a contributing guide.

**Comment by egabancho** [comment]
I don't see how making a contributing guide is related with having travis builds

**Comment by frecar** [comment]
No, it's more related to the other PR about committ messages etc.

About the travis build, I don't see any good reason for it other than "the other repos are using it" ?

**Comment by crepererum** [comment]
This fork Obelix is maintained by the Invenio Software Collaboration (and copyrighted by CERN), a group that favors Travis. We (the I.S.C.) use it for all our projects and have reusable code and templates for this service.

I doubt that Frigg gives us a clear advantage, especially now that [we can use the container based infrastructure of Travis](https://github.com/inveniosoftware/invenio/pull/3371). The clear downside of Frigg is the beta phase and the Invenio Team does not have the resources to fight yet another unfinished software.

Furthermore, Travis is operated by a neutral party and I can see a clear conflict of interest when it comes to Frigg.

**Comment by frecar** [comment]
It is not correct that it is copyrighted by CERN, it is a split between CERN and me. 

I think that a reasonable compromise would be to run both CI-systems side by side?

**Comment by ddaze** [comment]
I don’t see a problem with having both of it, doubled tested doesn’t hurt.

**Comment by crepererum** [comment]
:+1: seems legit, adding another (different) system might catch different bugs

**Comment by frecar** [comment]
Great! :)

**Pull request merged**
