### PR TITLE
global: command line argument parser improvements

### PR DESCRIPTION
**Pull request by ddaze**
* Parses arguments in a safer way using args4j.

* Adds description of the command line arguments.

Signed-off-by: David Zerulla <ddaze@outlook.de>

### CODE REVIEW

**Comment by frecar** [comment]
Is it reasonable to add some tests for this? :) So we can detect if anyone removes or changes arguments? :)

**Comment by egabancho** [comment]
I agree, if we refactor some functionality we should add test before changing anything.

@ddaze can you add some tests to cover your changes?

**Comment by frecar** [comment]
Any update or comment on this @ddaze ? :)

**Comment by ddaze** [comment]
No, but I think I have time next week.

**Comment by ddaze** [comment]
@frecar now with tests.

**Comment by frecar** [comment]
Perfect, thank you! :dancers:

**Pull request merged**
